#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4.1cvs on Sat Aug 26 21:00:33 2006

import wx

class AboutDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        self.title = kwds['about_title']
        self.text = kwds['about_text']
        del(kwds['about_title'], kwds['about_text'])
        # begin wxGlade: AboutDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, "Titel", style=wx.ALIGN_CENTRE)
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "text", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.bitmap_button_1 = wx.BitmapButton(self, -1, wx.Bitmap("/home/tweimann/workspace/wws/icon/commit.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_1 = wx.StaticBitmap(self, -1, wx.Bitmap("/home/tweimann/workspace/wws2/images/PythonPowered.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_2 = wx.StaticBitmap(self, -1, wx.Bitmap("/home/tweimann/workspace/wws2/images/wxPyButton.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_4 = wx.StaticBitmap(self, -1, wx.Bitmap("/home/tweimann/workspace/wws2/images/built_with_wx.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_3 = wx.StaticBitmap(self, -1, wx.Bitmap("/home/tweimann/workspace/wws2/images/wxglade.png", wx.BITMAP_TYPE_ANY))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.aboutClose, self.bitmap_button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AboutDialog.__set_properties
        self.SetTitle(u"Über ...")
        self.SetSize((500, 300))
        self.SetFocus()
        self.label_1.SetMinSize((325, 15))
        self.label_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.bitmap_button_1.SetMinSize((56, 24))
        self.bitmap_1.SetToolTipString("http://www.python.org")
        self.bitmap_2.SetToolTipString("http://www.wxpython.org")
        self.bitmap_4.SetToolTipString("http://www.wxwidgets.org")
        self.bitmap_3.SetToolTipString("http://wxglade.sourceforge.net")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AboutDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.label_1, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_3.Add(self.text_ctrl_1, 1, wx.ALL|wx.EXPAND, 5)
        sizer_3.Add(self.bitmap_button_1, 0, wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 5)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add(self.bitmap_1, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 5)
        sizer_2.Add(self.bitmap_2, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 5)
        sizer_2.Add(self.bitmap_4, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 5)
        sizer_2.Add(self.bitmap_3, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 5)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade
        self.label_1.SetLabel(self.title)
        self.text_ctrl_1.SetValue(self.text)

    def aboutClose(self, event): # wxGlade: AboutDialog.<event_handler>
        self.Destroy()

# end of class AboutDialog


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    dialog_1 = AboutDialog(None, -1, "", about_title = 'Testtext', about_text = 'bla bla\n')
    app.SetTopWindow(dialog_1)
    dialog_1.Show()
    app.MainLoop()
