#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4.1cvs on Sun Aug 20 08:53:23 2006

import wx

class ConfDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        self.parent = args[0]
        # begin wxGlade: ConfDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.label_1 = wx.StaticText(self, -1, u"Einstellungen für das Warenwirtschaftssystem:", style=wx.ALIGN_CENTRE)
        self.button_1 = wx.Button(self, -1, "Abbruch")
        self.bitmap_button_1 = wx.BitmapButton(self, -1, wx.Bitmap("/home/tweimann/workspace/wws/icon/commit.png", wx.BITMAP_TYPE_ANY))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onCancel, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.onOK, self.bitmap_button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ConfDialog.__set_properties
        self.SetTitle("Konfiguration")
        self.SetSize((377, 582))
        self.label_1.SetMinSize((390, 20))
        self.label_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.button_1.SetMinSize((88, 30))
        self.bitmap_button_1.SetMinSize((88, 30))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ConfDialog.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.label_1, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
        self.panel_1.SetAutoLayout(True)
        self.panel_1.SetSizer(sizer_3)
        sizer_3.Fit(self.panel_1)
        sizer_3.SetSizeHints(self.panel_1)
        sizer_2.Add(self.panel_1, 1, wx.EXPAND, 0)
        sizer_4.Add(self.button_1, 0, wx.ALL|wx.ADJUST_MINSIZE, 5)
        sizer_4.Add((20, 20), 1, wx.ADJUST_MINSIZE, 0)
        sizer_4.Add(self.bitmap_button_1, 0, wx.ALL|wx.ADJUST_MINSIZE, 5)
        sizer_2.Add(sizer_4, 0, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade
        sizers = []
        self.labels = []
        self.texts = []
        i = 0
        for opt in self.parent.set_edit:
            if type(self.parent.set[opt]) == bool:
                if self.parent.set[opt]:
                    _opt = u'ja'
                else:
                    _opt = u'nein'
            else:
                _opt = str(self.parent.set[opt])
            sizers.append(wx.BoxSizer(wx.HORIZONTAL))
            self.labels.append(wx.StaticText(self.panel_1, -1, opt, size = (100, 25), style = wx.ALIGN_LEFT))
            self.texts.append(wx.TextCtrl(self.panel_1, -1, _opt, size = (100, 25)))
            sizers[i].Add(self.labels[i], 0, wx.ALL|wx.ADJUST_MINSIZE, 5)
            sizers[i].Add(self.texts[i], 0, wx.ALL|wx.ADJUST_MINSIZE, 5)
            sizer_3.Add(sizers[i])
            i += 1
        self.Layout()
        
    def onCancel(self, event): # wxGlade: ConfDialog.<event_handler>
        self.Destroy()

    def onOK(self, event): # wxGlade: ConfDialog.<event_handler>
        print "Event handler `onOK' not implemented!"
        event.Skip()

# end of class ConfDialog


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    conf_dialog = ConfDialog(None, -1, "")
    app.SetTopWindow(conf_dialog)
    conf_dialog.Show()
    app.MainLoop()
